@startuml SQ
autonumber
title SD10.1. Tạo giao dịch
actor "Actor" as actor
boundary "TransactionView" as view
boundary "TransactionCreateView" as createView
control "TransactionController" as controller
entity "TransactionRepository" as model
database "Database" as database
activate actor
actor -> view : click create button
activate view
view -> createView: redirect to create page
activate createView
actor -> createView: enter data...
deactivate actor
createView -> controller : call api POST /create
activate controller
controller -> model : inject repository
activate model
model -> database : create data
activate database
database --> model : callback
deactivate database
model --> controller : callback
deactivate model
controller --> createView : return message
deactivate controller
createView -> createView : display message
createView -> view : redirect to list page
deactivate createView
view -> controller : call api GET /list
activate controller
controller -> model : inject repository
activate model
model -> database : find data
activate database
database --> model : return data
deactivate database
model --> controller : return list transactions
deactivate model
controller --> view : return list transactions
deactivate controller
view -> view: update display
activate view
deactivate view
deactivate view
@enduml