@startuml SQ
autonumber
title SD28.1. Thêm tài khoản
actor "Actor" as actor
boundary "NotePermissionView" as view
control "ProjectPermissionController" as controller
entity "ProjectPermissionRepository" as model
database "Database" as database
activate actor
actor -> view: click add button
activate view
view -> view: open add dialog
actor -> view: choose account
deactivate actor
view -> controller: call api POST /create
activate controller
controller -> model: inject repository
activate model
model -> database: add account
activate database
database --> model: callback
deactivate database
model --> controller: callback
deactivate model
controller --> view: return message
deactivate controller
view -> view: display message
view -> controller: call api GET /list
activate controller
controller -> model: inject repository
activate model
model -> database: find data
activate database
database --> model: return data
deactivate database
model --> controller: return list objects
deactivate model
controller --> view: return list
deactivate controller
view -> view: display data
activate view
deactivate view
deactivate view
@enduml